import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'

const Manropef = Manrope({ 
  weight: '800',
  variable: '--font-Manropef',
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Adivice Generator app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${Manropef.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
